### ISSUE TITLE
Support for a Predefined List of Video URLs

### ISSUE THREAD

**Issue by ShiguriVR** [synergiance/SynMediaPlayer#14] opened 2021-10-17 06:57 UTC
As a sort-of extra feature that can be included in the prefab, it would be nice to be able to add a list of predefined video items in a scrollable list that people can one-click start. This is something I've seen in worlds using other players so people can quickly choose music or a livestream without needing to look it up and enter the URL.

It should work by adding items to the list with a simple title and clicking on that item tells the player to start a predefined URL.

This feature should be optional and be a disabled object by default I imagine. Just there for those that would like to use it.

**Comment by synergiance** [comment] 2021-10-18 03:54
This is technically a duplicate of some of the functionality of Issue #13 but it has a better description. Keeping it open.

**Comment by synergiance** [comment] 2021-11-02 06:18
After re-reading this, I've realized that this feature won't be available on GitHub.

**Closed as completed by synergiance** 2021-11-02 06:18 UTC
Labels: duplicate, enhancement
